### ISSUE TITLE
Add  About Us, Contact Us, FAQ, and Footer Sections

### ISSUE THREAD

**Issue by Coderamrish** [Jaishree2310/GlassyUI-Components#12]
About Us: Introduce the project’s mission, team members, and future vision with engaging visuals.
Contact Us: Add a contact form (name, email, message) and provide social media links, email, and phone number.
FAQ: Implement an accordion-style FAQ to answer common user questions.
Footer: Design a footer with navigation links, social media icons, and copyright info, ensuring responsiveness.

**Comment by Jaishree2310** [comment]
Hey @Coderamrish, All the details mentioned in the GitHub repo don't require the footer section, for contact GitHub discussions are open. Thank you for taking an interest would love more to know how your contribution can add value to the project.

**Comment by vigneshbirru** [comment]
"I’d be happy to help with this issue, let me know how I can get started!"

**Comment by Jaishree2310** [comment]
> "I’d be happy to help with this issue, let me know how I can get started!"

You can check out other issues. This one seems already present.
