### ISSUE TITLE
Add official logo in Nav bar

### ISSUE THREAD

**Issue by justynigam** [Jaishree2310/GlassyUI-Components#121]
- if u add logo then it will look more enhance

**Comment by justynigam** [comment]
Im doing bruh

**Comment by Jaishree2310** [comment]
@justynigam I have assigned this issue to you. Make sure you keep giving updates on your work.
Happy coding!

**Comment by prisha-sh** [comment]
hey @Jaishree2310 
kindly assign me this task i'll be sharing the solution asap!!

**Comment by Avansh2006** [comment]
Hii @Jaishree2310 !!
Can you please assign this issue to me, so that I can start working on it....
