### ISSUE TITLE
[FEATURE] Addind a scroll down button for easy scrolling

### ISSUE THREAD

**Issue by banasmita24** [Jaishree2310/GlassyUI-Components#128]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

Frustrating to manually scroll through the page, as it can be inefficient. Users may lose their place, especially when accessing content on mobile devices or when they need to revisit a specific section. Navigating long content is challenging without a structured way to scroll down the page incrementally.

### Proposed Solution

I propose the addition of a scroll down button that allows users to easily navigate through the content page-by-page. This button could be fixed to the side of the screen and enable users to scroll down one full screen at a time with a single click. A possible reference could be the scroll button used by many e-readers and document viewers, which implement page-by-page navigation.

### Screenshots

Before:
![image](https://github.com/user-attachments/assets/8ac71c5c-80a8-4d38-a3b4-d6c752555939)

After:
![image](https://github.com/user-attachments/assets/da46512c-c9db-42fa-95c9-0329ee455be3)

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this (issue will not be assigned if this is skipped)

Potential libraries or code references could include JavaScript's [ window.scrollBy() ] function for smooth scrolling or using CSS for fixed positioning of the button. An existing library like Smooth Scroll could also be used to implement a seamless transition between page sections.

**Comment by banasmita24** [comment]
Hi, Can u please add hactoberfest-accepted and the respective level.

**Comment by Jaishree2310** [comment]
@banasmita24 I have assigned this issue to you. Make sure you keep giving updates on your work.
Happy coding!

**Comment by banasmita24** [comment]
Hi, there was a issue while running the code. This was because 'HiOutlineWrenchScrewdriver' was not imported from 'react-icons/hi2'. Solved that now! Now working on the scroll button.
![image](https://github.com/user-attachments/assets/7460e81a-5569-409e-b3ca-5c287a1a3796)
