### ISSUE TITLE
Add Top scroll button to the website

### ISSUE THREAD

**Issue by rutikakengal** [Jaishree2310/GlassyUI-Components#13]
Add gssoc-ext , hactoberfest accepted, level labels @Jaishree2310 Assign me i like to work on it

**Comment by Jaishree2310** [comment]
@rutikakengal, Thank you for contributing to the project. I have assigned you, you can start working now. 
Please make sure to keep us in the loop about your progress.

**Comment by rutikakengal** [comment]
Ok

**Comment by rutikakengal** [comment]
@Jaishree2310 where is html code and I m not able to see the code in vs code to make changes

**Comment by zadescoxp** [comment]
Please check your PR it's done
