### ISSUE TITLE
[BUG] Unable to view title of component due to font colour

### ISSUE THREAD

**Issue by sanchitgumber** [Jaishree2310/GlassyUI-Components#162]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Issues with Title/Heading Visibility on the Card Component Page

The **Title/Heading** of the Card Component page has a dark background, making it harder to read. The same issue is present with the **Basic Usage** title on the same page.

### Screenshots

<img width="1470" alt="Screenshot 2024-10-15 at 5 04 20 PM" src="https://github.com/user-attachments/assets/0679fe17-c705-4516-9323-49f934481355">

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this (issue will not be assigned if this is skipped)

Will change tailwind classes to increase readiablity

**Comment by RajeshTechForge** [comment]
I am interested to work on this issue, please assign me.

**Comment by Jaishree2310** [comment]
@RajeshTechForge This is first come first serve basis

**Comment by Jaishree2310** [comment]
@sanchitgumber I have assigned this issue to you. Make sure you keep giving updates on your work.
Happy coding!

**Comment by sanchitgumber** [comment]
@Jaishree2310 Thank You for assiging! I have raised a PR
