### ISSUE TITLE
[BUG] The table ui format is not same throughout all the components and TextArea ui is much white

### ISSUE THREAD

**Issue by nidhi2026** [Jaishree2310/GlassyUI-Components#164]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

Table ui formatting is not same throughout the project. Also the title name of many components page is not same. This unevenness is not much pleasant to eyes. It hinders in uniformity of looks of all pages. Also the text Area page is unlike other pages, the white text are not much dominant in such light page, it needs to be like other pages.

### Steps to Reproduce

Include any relevant details like:

- Toast, slider, Card, speed dials, textArea etc components
- The format in frontend of those components

### Screenshots

![image](https://github.com/user-attachments/assets/78d6b00d-b771-4eab-a45c-3ede3e77f400)
and in some
![image](https://github.com/user-attachments/assets/b2693e26-0772-4efc-a326-a28e800b2952)

for title
![image](https://github.com/user-attachments/assets/32bfcb8e-8646-4ddd-a23b-7c3b52aa8fe5)
and in some
![image](https://github.com/user-attachments/assets/eda3388f-bc15-489a-af6d-3f275ea13465)

textArea component
![image](https://github.com/user-attachments/assets/6be729b3-f181-48a3-9e7a-07f0b03d51c2)

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

I will change the css style to match throughout the project, (I will go with the first photo of ss above for table)

**Comment by Jaishree2310** [comment]
@nidhi2026 I have assigned this issue to you. Make sure you keep giving updates on your work.
Happy coding!

**Comment by nidhi2026** [comment]
@Jaishree2310 There are two people/issues working on card components, so shall i skip it
