### ISSUE TITLE
Add Glassy Modal component

### ISSUE THREAD

**Issue by mdrehan369** [Jaishree2310/GlassyUI-Components#17]
the glassy modal component details page is missing so i can add it to make it functional

**Comment by mdrehan369** [comment]
Please assign this issue to me under Hactoberfest 2024

**Comment by Jaishree2310** [comment]
Hey @mdrehan369, I have assigned this issue to you. Please give update about your progress.

**Comment by Jaishree2310** [comment]
Link to #5
