### ISSUE TITLE
[FEATURE]  Adding Separate Sign In option at the navigation bar

### ISSUE THREAD

**Issue by JyothiPriya5** [Jaishree2310/GlassyUI-Components#172]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

I have seen that there is no sign in option at the navigation bar 

### Proposed Solution

If you could assign me this issue i will provide better UI with the Sign In option
 

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this (issue will not be assigned if this is skipped)

Please assign me this issue, I could work better on this

**Comment by Jaishree2310** [comment]
@JyothiPriya5  I have assigned this issue to you.
Happy coding!

**Comment by Jaishree2310** [comment]
@JyothiPriya5 Could you complete it within 2 days for better contribution? I am in the Loop of checking all the PR's and issues very carefully so I have to keep the consistency maintained.

**Comment by JyothiPriya5** [comment]
@Jaishree2310 Sure.!!
