### ISSUE TITLE
[BUG] Git contributors page not having complete data

### ISSUE THREAD

**Issue by Akshithsaai** [Jaishree2310/GlassyUI-Components#174]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

The Git contribution page is showing a part of data. 
example : there are 35 contributors now. but the page is displaying only 30 . 

I want refactor the code to show the complete data. 

### Steps to Reproduce

Compare the contributors on repo page and in website.

### Website Data
![image](https://github.com/user-attachments/assets/f04f1a19-fdaa-4ee8-b6d9-945011725ee9)

### Repo's Data
![image](https://github.com/user-attachments/assets/de91a45a-3c12-41d1-a5af-ccf850ebc356)

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

I want to update the fetch request so that the api is called for entire data. 

@Jaishree2310 I have read the documentation for the api and I can update it optimally, Please assign me this issue.

**Comment by Jaishree2310** [comment]
@Akshithsaai I have assigned this issue to you. Make sure you keep giving updates on your work.
Happy coding!
