### ISSUE TITLE
[BUG] Read me live demo redirects to invalid domain

### ISSUE THREAD

**Issue by sanchitgumber** [Jaishree2310/GlassyUI-Components#177]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

Live demo in read me redirects to *https://glassyui.com* instead of **glassyui.vercel.app**

### Steps to Reproduce

Include any relevant details like:
 
Click on link in ReadMe Preview

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

Update Read me with correct url

**Comment by Jaishree2310** [comment]
@sanchitgumber I have assigned this issue to you. Make sure you keep giving updates on your work.
Happy coding!

**Comment by sanchitgumber** [comment]
@Jaishree2310 I have made the chanages. Please review.
