### ISSUE TITLE
Feature Request: Adding transitions to some text

### ISSUE THREAD

**Issue by NazTM** [Jaishree2310/GlassyUI-Components#21]
I'd like to work on adding fade transitions to some of the text for a smoother experience. I may also adjust the alignment for "Glassmorphic Components". I'd like to be assigned to work on this for my first contribution for gssoc.

**Comment by NazTM** [comment]
Please assign the label gssoc-ext, not gssoc

**Comment by Jaishree2310** [comment]
@NazTM, Done

**Comment by NazTM** [comment]
Created pull request

**Comment by NazTM** [comment]
Created pull request @Jaishree2310
