### ISSUE TITLE
[BUG] <description> Remove footer from when clicking on the components

### ISSUE THREAD

**Issue by Jaishree2310** [Jaishree2310/GlassyUI-Components#233]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

The footer should only be seen in the main page not all the components page

### Steps to Reproduce

Include any relevant details like:

- What page you were on...
- What you were trying to do...
- What went wrong...

### Do you want to work on this issue?

No

**Comment by sujalcharati** [comment]
@Jaishree2310 please can i be assigned for the given issue?

**Comment by Jaishree2310** [comment]
@sujalcharati Make sure it does not remove from the main page it should be minimalist and clean ui look .
