### ISSUE TITLE
[FEATURE] <description> Pricing Plan Components need extra attention

### ISSUE THREAD

**Issue by Jaishree2310** [Jaishree2310/GlassyUI-Components#234]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

Components are not following the order of component 
Basic Usage
Props
Customizable component
Theme 
Copy code 

### Proposed Solution

Take the example of the button component

### Do you want to work on this issue?

No

**Comment by AdityaInnovates** [comment]
I have reviewed the pricing-details page. Please assign the issue to me so I can start fixing it.

**Comment by Jaishree2310** [comment]
@AdityaInnovates done

**Comment by amanreddy77** [comment]
hey @Jaishree2310 if this issue still persist i would like to work on it

**Comment by AdityaInnovates** [comment]
hello, @Jaishree2310. I am still refactoring the code for the pricing details page. I need a little more time to complete everything.
