### ISSUE TITLE
Create Discussion Template for Block Requests

### ISSUE THREAD

**Issue by abhishekHegde2000** [Jaishree2310/GlassyUI-Components#24]
**Description:**
Create a discussion template for block requests to standardize the format and ensure all necessary information is provided. This template will be added to the `.github/DISCUSSION_TEMPLATE/` directory.

**Tasks:**
1. **Create Directory:**
   - Create the `.github/DISCUSSION_TEMPLATE/` directory.

2. **Create Template File:**
   - Create a `blocks-request.yml` file in the `.github/DISCUSSION_TEMPLATE/` directory with the necessary template content for block requests.

**Files to Modify:**
- Create `.github/DISCUSSION_TEMPLATE/blocks-request.yml`

**Benefits:**
- Standardizes the format for requesting new blocks, ensuring clarity and completeness.
- Facilitates effective communication and documentation of block requests within the project.

**Comment by abhishekHegde2000** [comment]
@Jaishree2310 Can you please Assign this to me?

**Comment by rajesh-puripanda** [comment]
Alert component for success/error/warning/info. Glass backdrop with icon + dismiss action. Timed auto-dismiss option. @Jaishree2310 please assign.
