### ISSUE TITLE
[BUG] <description>REMOVE @2023 COPYWRITE FROM THE FOOTER

### ISSUE THREAD

**Issue by Jaishree2310** [Jaishree2310/GlassyUI-Components#241]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

check the footer and remove copywrite 2023 

### Steps to Reproduce

Include any relevant details like:

- What page you were on...
- What you were trying to do...
- What went wrong...

### Do you want to work on this issue?

No

**Comment by Hemraj-7** [comment]
Hey @Jaishree2310 , I want to work on this
please assign me

**Comment by Jaishree2310** [comment]
@Hemraj-7 Done
