### ISSUE TITLE
Enhance footer styling

### ISSUE THREAD

**Issue by Sawan-Kushwah** [Jaishree2310/GlassyUI-Components#246]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

footer is not looking good

### Steps to Reproduce

go to home page

### Screenshots

![image](https://github.com/user-attachments/assets/7245381b-5df7-49c0-adfe-34d057656bdb)

### Do you want to work on this issue?

Yes

**Comment by Naveenkumar30838** [comment]
want to work on this issue
