### ISSUE TITLE
BUG:title logo 

### ISSUE THREAD

**Issue by Risheendra183** [Jaishree2310/GlassyUI-Components#25]
![Screenshot 2024-10-04 231305](https://github.com/user-attachments/assets/65cb293d-1997-428e-bd83-a0fae50fef27)
i would like to add the logo for the website .
plz assign me 
Add labels gssoc-ext, Hactoberfest accepted and levels @Jaishree2310 assign me i like to work on it

**Comment by Jaishree2310** [comment]
@Risheendra183 Assigned you can start by approving logo design.

**Comment by caliginosusmoon** [comment]
Is this issue fixed? If not, can you please assign this to me? @Jaishree2310

**Comment by Risheendra183** [comment]
> @Risheendra183 Assigned you can start by approving logo design.
![image](https://github.com/user-attachments/assets/84ec07cc-437a-4915-8853-1424d302a0c1)
can u check this once

**Comment by Risheendra183** [comment]
can i proceed with that

**Comment by rajesh-puripanda** [comment]
Accordion component — expand/collapse with smooth height animation, multiple/ single mode, keyboard navigable. @Jaishree2310 please assign.
