### ISSUE TITLE
✨ [feature enhancement] : add navbar ✨

### ISSUE THREAD

**Issue by snehaapratap** [Jaishree2310/GlassyUI-Components#26]
navbar can be added to enhance the website.
![image](https://github.com/user-attachments/assets/1caad560-7ba9-48a6-9243-2b015f1a462a)
please assign me this task.
thank you !

**Comment by rajesh-puripanda** [comment]
Toggle/Switch with glass aesthetic — smooth slide animation, accessible (role=switch, aria-checked). @Jaishree2310 please assign.
