### ISSUE TITLE
[BUG] `package.json` missing Zod as dependency

### ISSUE THREAD

**Issue by RajeshTechForge** [Jaishree2310/GlassyUI-Components#262]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

Need to add "zod" as a dependency in "package.json" because npm install is not installing it so it giving error on `npm start`.

### Steps to Reproduce

Clone the project, open the terminal in the project directory, and run `npm install`. Then run `npm start`.

### Screenshots

![Screenshot 2024-10-18 202336](https://github.com/user-attachments/assets/a2329d5f-981b-4ccc-a864-1f748dbfbe01)

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

Updating `package.json` by adding it.

**Comment by sujalcharati** [comment]
@RajeshTechForge  hey, never mind i have done that once pr gets merged its not needed..

**Comment by Jaishree2310** [comment]
@sujalcharati thank you
