### ISSUE TITLE
the text  is  not animated on the page of contributors ...  text is "Our Amazing Contributirs"

### ISSUE THREAD

**Issue by 2004pra** [Jaishree2310/GlassyUI-Components#263]
As i am sharing you ṭhe screenshot of  contributors page --> i would like to redesign the text and want to  provide an animation to this particularly  ..
Please assign me this issue under gsssoc extd 2024, hacktober fest.. atleast make it  level 2 if you want because animation designing is a bit hard ........
@Jaishree2310 
![Screenshot 2024-10-18 230853](https://github.com/user-attachments/assets/ab32f7e4-40e8-4f67-9efb-ba434aec950a)

**Comment by Jaishree2310** [comment]
@2004pra Make sure you stick with the glassmorphism theme

**Comment by 2004pra** [comment]
for sure ......

**Comment by 2004pra** [comment]
sorry i am not able to complete this issue because i dont know anything about react
