### ISSUE TITLE
[bug] : Getting 404 error when click on models and navigation 

### ISSUE THREAD

**Issue by mohitahlawat2001** [Jaishree2310/GlassyUI-Components#27]
I would like to solve this issue, please assign it to me

**Comment by Jaishree2310** [comment]
@mohitahlawat2001, It needs to completed like other components.

**Comment by mohitahlawat2001** [comment]
sure

**Comment by Jaishree2310** [comment]
@mohitahlawat2001, assigned.
Happy Coding!

**Comment by rajesh-puripanda** [comment]
Input component with floating label + glass styling. Error state, disabled state, icon support. React Hook Form compatible. @Jaishree2310 please assign.
