### ISSUE TITLE
[FEATURE] Add a new page to display all contributors ⭐

### ISSUE THREAD

**Issue by Subhajit-2023-44** [Jaishree2310/GlassyUI-Components#273]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

I want to add a page to showcase all the contributors of this website..

@jai please assign me this task.

![image](https://github.com/user-attachments/assets/17626d4f-8d5f-413d-bfb9-8fc83b4f5ac0)

### Proposed Solution

.

### Do you want to work on this issue?

No

**Comment by Subhajit-2023-44** [comment]
@Jaishree2310

**Comment by Subhajit-2023-44** [comment]
@Jaishree2310

**Comment by Jaishree2310** [comment]
@Subhajit-2023-44  It already exist in OurContributions
