### ISSUE TITLE
[FEATURE] Add Translation Tool ⭐

### ISSUE THREAD

**Issue by Subhajit-2023-44** [Jaishree2310/GlassyUI-Components#274]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

I want to add a Translation Tool(all language) properly.

@jaiPA please assign me this task.

![image](https://github.com/user-attachments/assets/ef55b915-bedd-4c07-8dcb-7632f1661d28)

### Proposed Solution

.

### Do you want to work on this issue?

No

**Comment by ishivansmishra** [comment]
@Subhajit-2023-44 @Jaishree2310 Please assign this under gssoc ext and hacktyoberfest and give me a level 2

**Comment by Subhajit-2023-44** [comment]
@Jaishree2310

**Comment by Jaishree2310** [comment]
@Subhajit-2023-44 In which language?

**Comment by Jaishree2310** [comment]
Have not planned this

**Comment by Subhajit-2023-44** [comment]
> @Subhajit-2023-44 In which language?

@Jaishree2310 All languages

**Comment by Jaishree2310** [comment]
but the code is going to be used in english language

**Comment by Subhajit-2023-44** [comment]
> but the code is going to be used in english language

Yes please assign me
