### ISSUE TITLE
STRUCTURE THE CONTRIBUTOR SECTION 

### ISSUE THREAD

**Issue by alo7lika** [Jaishree2310/GlassyUI-Components#280]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate.

### Description

Structuring the Contributor Section in your README file is crucial for recognizing and celebrating the individuals who have contributed to the project. A well-organized Contributor Section showcases the effort of each contributor, encouraging future participation and enhancing community engagement. A clear and visually appealing structure helps highlight each contributor's contributions and provides an easy reference for others to see who has been involved. It not only creates a sense of community but also motivates contributors to stay active and encourages new contributors to join, leading to the overall growth and improvement of the project.

### Steps to Reproduce

Relevant Details for Structuring the Contributor Section:
1. Go to the README file of the GlassyUI-Components repository.
2. Observe the absence of a dedicated Contributor Section.
3. Note the lack of visual appeal and organization in the current format.
4. Identify the need for a more structured representation of contributors.

### Screenshots

N/A

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

To address the need for a structured Contributor Section, I would:

1. Create a new section titled "Our Valuable Contributors" in the README.
2. Utilize a visually appealing format to list contributors, including their avatars, GitHub usernames, and profile links.
3. Ensure that the contributors are dynamically linked to their GitHub profiles to promote engagement.
4. Reference the existing contributor data using GitHub's API or manually input the details if necessary.
5. Review and test the changes to ensure they render correctly in the Markdown format.
6. Document the updates made to the README and inform other contributors of the newly structured section.

**Comment by alo7lika** [comment]
ADD LABELS HACKTOBERFEST AND GSSOC EXT 24
ASSIGN ME THE TASK @Jaishree2310 
Thank you!

**Comment by Jaishree2310** [comment]
@alo7lika please do not use capital words
