### ISSUE TITLE
[BUG] Update Footer Year to 2024

### ISSUE THREAD

**Issue by neeru24** [Jaishree2310/GlassyUI-Components#283]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

I would like to address an issue in the footer of the project. Currently, the text reads "All rights reserved 2023."

### Steps to Reproduce

I propose changing it to "All rights reserved 2024" to reflect the current year.

Could you please assign me this issue? I will modify it accordingly and submit a PR as soon as it's done.

Thank you!

### Screenshots

![image](https://github.com/user-attachments/assets/91663af2-07fe-4611-8dc1-4efa81d07876)

### Do you want to work on this issue?

Yes

**Comment by stevenanthonyrevo** [comment]
Hey @neeru24, 

I just noticed the bug you mentioned. 

My confusion was related to the deployment version ([glassyui.vercel.app](https://glassyui.vercel.app/)) being outdated.

I had created the same issues #267 and #268 but I think the footer year is still in need of being updated 👍

Thank you @Jaishree2310 for merging my the latest changes to the footer. 

For more details on were the date update can be done.

See line [39](https://github.com/Jaishree2310/GlassyUI-Components/blob/main/src/components/Footer.tsx#L39) requires the update. 

Good luck with the update @neeru24, passing the issue to you. 

Thanks everyone, Happy Hacktoberfest!

**Comment by Jaishree2310** [comment]
@neeru24 Could you complete it within 2 days for better contribution? I am in the Loop of checking all the PR's and issues very carefully so I have to keep the consistency maintained.

**Comment by Jaishree2310** [comment]
@neeru24 This issue is done by other contributor in his footer issue so its closed now.
Happy Coding! Thank you.

**Comment by Jaishree2310** [comment]
https://github.com/Jaishree2310
