### ISSUE TITLE
Integrating Payment Gateway

### ISSUE THREAD

**Issue by Dhruv80576** [Jaishree2310/GlassyUI-Components#291]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

I would like to integrate payment gateway on donation page instead of just collecting response from the user.

### Proposed Solution

Integrating stripe payment gateway with nextjs and implementing webhooks for secure transaction.

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this (issue will not be assigned if this is skipped)

I have previously worked on integrating payment gateway in applications.

![Screenshot_20241021_094423](https://github.com/user-attachments/assets/706f1f93-6f4d-4cef-b363-87566bcaecac)

**Comment by Jaishree2310** [comment]
@Dhruv80576 not planned this yet
