### ISSUE TITLE
[BUG] Fix the Search component input on "/components" page

### ISSUE THREAD

**Issue by AdityaInnovates** [Jaishree2310/GlassyUI-Components#299]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

The Search component input on the "/components" requires a UI update to align with the overall page design. This update aims to improve visual consistency and user experience without altering the component's functionality.

### Screenshots

<img width="1512" alt="Screenshot 2024-10-21 at 3 23 43 PM" src="https://github.com/user-attachments/assets/d8fb8484-6c81-4862-88fa-0d6ded77835c">

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

I can update the input with **glassmorphism** design and update the overall spacing for a **better UI**.
I am submitting it for **hacktoberfest**.

**Comment by Jaishree2310** [comment]
@AdityaInnovates Could you complete it within 2 days for better contribution? I am in the Loop of checking all the PR's and issues very carefully so I have to keep the consistency maintained.

**Comment by akshayad2006-cmd** [comment]
Hi @Jaishree2310 I want to contribute can you please assign it to me
