### ISSUE TITLE
Button Text Color Changes on Different Pages

### ISSUE THREAD

**Issue by Himmiee** [Jaishree2310/GlassyUI-Components#30]
Description
The "Back to Components" button isn't staying consistent with its text color across different pages. On some pages, it shows up in black (as expected), but on others, it turns white, making it a bit hard to read when the background is lighter.

What is Expected
The button text should always be black, no matter which page I'm on.
What Actually Happens
On the component page, the button text looks fine (black).
On the text area page, the text turns white, which makes it hard to see.

Current State
![714ED226-649E-4F6E-814E-8523D70DEB57_1_201_a](https://github.com/user-attachments/assets/6692a010-38b9-47eb-8fc9-0be65ecbc688)

Proposed State
![580F3313-DFD2-450A-8440-AAE0755C135D_1_201_a](https://github.com/user-attachments/assets/c0080047-d7d1-4637-ab67-86186175d5ab)

**Comment by arpit74170** [comment]
please assign this task to me

**Comment by lokeshjakhar7781** [comment]
please assign this task to me

**Comment by arpit74170** [comment]
How can i check my score ant the contribution that i have done is it level 1 or 2?

**Comment by Jaishree2310** [comment]
> How can i check my score ant the contribution that i have done is it level 1 or 2?

Level1 i have added!

**Comment by rajesh-puripanda** [comment]
Card component — glass container with props for blur, opacity, border gradient. Compound component for Card.Header/Media/Body. @Jaishree2310 please assign.
