### ISSUE TITLE
[FEATURE] <description>Added MIT License

### ISSUE THREAD

**Issue by Dipanita45** [Jaishree2310/GlassyUI-Components#301]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

It protect the project  from causing any damage

Please assign me the issue 

### Proposed Solution

Protective

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this (issue will not be assigned if this is skipped)

Added MIT License

**Comment by Jaishree2310** [comment]
@Dipanita45 not planned yet
