### ISSUE TITLE
The Props description is not correctly aligned

### ISSUE THREAD

**Issue by rishabhrawat05** [Jaishree2310/GlassyUI-Components#31]
Hi! @Jaishree2310 
I have found a issue with the props description section not completely showing up in mobile device.
Here is the screenshot of the problem
![Screenshot_2024_1005_211449](https://github.com/user-attachments/assets/eff97eef-ac72-4ef4-8dcb-20ba64bc9994)

Please assign this issue to me

**Comment by rajesh-puripanda** [comment]
Button component with glass morphism + variants (primary/secondary/ghost/icon). Forward ref + type-safe. @Jaishree2310 please assign.
