### ISSUE TITLE
Adding Favicon as per the website's theme

### ISSUE THREAD

**Issue by hetvipopat** [Jaishree2310/GlassyUI-Components#33]
I would like to add favicon to the website as per the theme and logo

Please add gssoc-ext 24 and hacktoberfest label and also level 1 or level 2 or level 3 label

**Comment by pameladeysarkar2003** [comment]
please assign me with the task @Jaishree2310

**Comment by Jaishree2310** [comment]
@pameladeysarkar2003, I guess this issue already exists and is assigned to someone, if it's not completed with in 5 days would assign you. Till then you can see other issues. Happy coding!

**Comment by rajesh-puripanda** [comment]
Navbar is static HTML — needs React component with routing. I'll create a GlassmorphismNavbar with responsive mobile drawer + active link highlighting. @Jaishree2310 please assign.
