### ISSUE TITLE
Enhancing readme.md 

### ISSUE THREAD

**Issue by neeru24** [Jaishree2310/GlassyUI-Components#34]
Hi, I’ve been exploring the project and appreciate the work you’ve done so far. I’d like to propose an update to the README.md file to provide a more comprehensive overview of the website like adding some emojis, animations, screenshots of the website if possible.

I believe these updates could enhance user understanding and engagement with the project. If you're open to it, I’d love to contribute.

I’m committed to continually improving the quality of our documentation.

Thank you!

![Uploading image.png…]()

**Comment by Jaishree2310** [comment]
@neeru24, Please keep me updated with the changes.
Happy Coding!

**Comment by AnujSaha0111** [comment]
Can you please assign it to me? I want to work on it.
