### ISSUE TITLE
No  Proper redirection to the pages !!

### ISSUE THREAD

**Issue by SrijaVuppala295** [Jaishree2310/GlassyUI-Components#354]
![image](https://github.com/user-attachments/assets/99287d71-0367-48e4-81c3-55f8cb45293e)

# By clicking on the become a contributor , it should redirect to github page , @Jaishree2310 , assign me under this issue !!

**Comment by Jaishree2310** [comment]
@SrijaVuppala295 Complete it next 2 days all the Issues Assigned to you please so that it will be easy for everyone to mark the task and your rank.

**Comment by SrijaVuppala295** [comment]
@Jaishree2310 , getting soo many errors while running the code , please fix it !!

**Comment by Jaishree2310** [comment]
@SrijaVuppala295 Go one by one and resolve the conflicts.

**Comment by SrijaVuppala295** [comment]
> @SrijaVuppala295 Go one by one and resolve the conflicts.

Mam Please add labels to the PR's ==> #381 ,  #382 ,  #383 , #384 , #385 , #386, #387 , #388,  #389 , #390, #394 , #393
 Please add labels and assign me !! Literally it took me many hours to do it !!! Kindly please understand and add the labels to all pr's .Without the labels , all my hardwork goes waste . I hope you understand !
