### ISSUE TITLE
Website doesn't have footer

### ISSUE THREAD

**Issue by Anjalee01** [Jaishree2310/GlassyUI-Components#39]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

Website does not have footer section, I want to add it.

### Proposed Solution

I will make a section which will have footer information

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this (issue will not be assigned if this is skipped)

I will make a section using HTML and design it with css and add js

**Comment by Jaishree2310** [comment]
@Anjalee01, In footer what are you going to add please mention.

**Comment by Anjalee01** [comment]
> @Anjalee01, In footer what are you going to add please mention.

@Jaishree2310  I will add some contact information like location, contact number and email. I will add subscribe to our newsteller option , some social media links and copyright.

**Comment by Jaishree2310** [comment]
> > @Anjalee01, In footer what are you going to add please mention.
> 
> @Jaishree2310 I will add some contact information like location, contact number and email. I will add subscribe to our newsteller option , some social media links and copyright.

I don't think so its planned yet.
