### ISSUE TITLE
BUG: Explore components not showing.

### ISSUE THREAD

**Issue by Jaishree2310** [Jaishree2310/GlassyUI-Components#427]
### Preliminary Check

- [X] I have searched the existing issues
- [X] This issue is reproducible

### Bug Summary

The home page is empty and site is not working as usual and not scrolling

### Steps to Reproduce

Go to home page

### Additional Information

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue
- [X] I can provide more details if needed

**Comment by Jaishree2310** [comment]
Anyone who can fix this will be beneficial. 
Thank you !!

**Comment by Jaishree2310** [comment]
@Gauravtb2253, @Sawan-Kushwah

**Comment by Somyajain2004** [comment]
Please Issues any remaining bugs or features
