### ISSUE TITLE
[FEATURE] Add Animation on the main page Card Element

### ISSUE THREAD

**Issue by ashish-um** [Jaishree2310/GlassyUI-Components#46]
### Is this a unique feature?

- [x] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

The main card element on the home page currently appears abruptly without any animation, leading to a jarring user experience. 

### Proposed Solution

I propose enhancing the user interface by adding a smooth animation effect where the card fades in and moves slightly upwards to its intended position. This will create a more polished, visually appealing experience.

### Screenshots

https://github.com/user-attachments/assets/0f4af23f-3226-4e50-8cee-0cb1fefaa3fb

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this (issue will not be assigned if this is skipped)

Proposed Solution:

- Implement a fade-in effect on the card when the page 
- Add a slight upward movement during the fade-in to give the card a smooth entry.
- Ensure the animation is subtle and doesn't detract from the overall user experience.

Hey @Jaishree2310 Please assign this task to me so that I can start working on it.
If there is any preference from your side, please tell me.
_**And also don't forget to add Labels on this Hactoberfest**_

**Comment by Jaishree2310** [comment]
@ashish-um, Done.
Happy Coding

**Comment by ashish-um** [comment]
@Jaishree2310 please also add the hacktoberfest labels :)
