### ISSUE TITLE
[FEATURE] <Preloader>

### ISSUE THREAD

**Issue by Jagpreet153** [Jaishree2310/GlassyUI-Components#52]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

Yes , adding a preloader will enhance user interest

### Proposed Solution

I would like to add a svg animated file which will render until the page is being loaded

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this (issue will not be assigned if this is skipped)

I would add a svg file in json format from lottie animation I would be using lottie dependency. And this file will be rendered in Home file using useEffect to check whether the page is loaded or not

**Comment by Jagpreet153** [comment]
@Jaishree2310 Assign it under Hacktoberfest

**Comment by Jaishree2310** [comment]
@Jagpreet153, Make sure you keep giving updates on your work.
Happy coding!
