### ISSUE TITLE
[FEATURE]  Add Glassmorphism Effect Generator Feature

### ISSUE THREAD

**Issue by VAmanjain** [Jaishree2310/GlassyUI-Components#54]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

The current repository contains a Glassmorphism effects component that allows users to apply predefined styles. However, there is no option for users to dynamically create their own custom Glassmorphism effects. This missing functionality limits users to preset effects, which may not always suit their specific design needs.

Adding a Glassmorphism Effect Generator will allow users to input their own values (e.g., blur, transparency, background color, shadow) and get the corresponding CSS styles. This feature will greatly enhance flexibility and user control when designing Glassmorphism effects.

### Feature Details:
1. **UI for Customization**:
   - Create a form interface where users can adjust Glassmorphism parameters:
     - **Blur** (Range slider: 0px - 50px)
     - **Opacity** (Range slider: 0 - 1)
     - **Background Color** (RGBA or HEX picker)
     - **Box Shadow** (Sliders for shadow blur, color, and offset)
     - **Border Radius** (Slider: 0px - 50px)
   
2. **Real-Time Preview**:
   - Integrate a real-time preview box that reflects changes as users adjust the parameters. The preview will update dynamically, showing users how their customized Glassmorphism effect looks.

3. **CSS Code Generator**:
   - As users adjust parameters, automatically generate the corresponding CSS code below the preview. Users will be able to copy this code with a single click.
   
4. **Integration**:
   - Incorporate the Glassmorphism Effect Generator into the existing Glassmorphism component or create a separate page for the generator.
   - Ensure a consistent design between the current components and the generator UI.

---

## Screenshots

1. **Initial UI Mockup**:
   - Sliders for adjusting blur, opacity, etc.
   - Color picker for background
   - Real-time preview box next to the sliders
   - Generated CSS box below the preview

### Do you want to work on this issue?

Yes

### Implementation Plan:

1. **UI Design**:  
   I would create a new component, `GlassmorphismGenerator.tsx`, that includes form inputs (sliders and color pickers) for adjusting Glassmorphism properties. For real-time preview, I will use a styled `div` that dynamically applies the CSS properties as the user adjusts the values.

2. **Real-Time CSS Generation**:  
   I will build a function to dynamically update the CSS properties based on the user inputs. This function will handle the values entered for blur, opacity, background color, and other parameters, and display the resulting CSS in a code box.

3. **CSS Copy Feature**:  
   To implement the copy feature, I will use JavaScript’s library `eact-copy-to-clipboard` API, allowing users to copy the generated CSS with a single button click.

4. **Integration with Current Repo**:  
   I will add a navigation link to access the new Glassmorphism Generator feature. It could either be integrated as a modal in the existing page or added as a separate page/route.

5. **References**:  
   - **React Sliders** for UI 
   - **CSS Preview**: The CSS string generation will be based on existing CSS properties used for Glassmorphism (e.g., `backdrop-filter`, `rgba`, `box-shadow`).
   - **Clipboard API**: For copying the CSS to the clipboard.

This approach will ensure a seamless integration of the feature with minimal changes to the core structure of the project.

**Comment by VAmanjain** [comment]
Hey @Jaishree2310  kindly assign this task to me.

**Comment by Jaishree2310** [comment]
@VAmanjain done

**Comment by VAmanjain** [comment]
Hey @Jaishree2310 Can you assign me this task under the hacktoctober fest ?

**Comment by VAmanjain** [comment]
@Jaishree2310  I have removed my assignment by mistake. Kindly Reassign it please.
