### ISSUE TITLE
[BUG] structure of code is not properly align in mobile view 

### ISSUE THREAD

**Issue by Sawan-Kushwah** [Jaishree2310/GlassyUI-Components#56]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

The code is not look good in mobile view 

### Steps to Reproduce

See on mobile 

### Screenshots

![Screenshot_20241007_172823](https://github.com/user-attachments/assets/b17a202d-d8c6-4669-af51-e8fab810dd42)

### Do you want to work on this issue?

Yes

**Comment by Jaishree2310** [comment]
@Sawan-Kushwah Assigned.
