### ISSUE TITLE
[BUG] Default React Logo in Favicon

### ISSUE THREAD

**Issue by Abheeshta-P** [Jaishree2310/GlassyUI-Components#58]
### Has this bug been raised before?

- [ ] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

The website currently uses the default React logo as its favicon. For a professional site, this can create a branding issue, as the favicon should ideally reflect the company or platform's identity rather than the technology stack.

### Steps to Reproduce

- Open the website.
- Check the favicon in the browser tab.

### Screenshots

![image](https://github.com/user-attachments/assets/21689f88-b878-46d4-b86e-7548d61018b4)

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

Replace the React logo favicon with the company’s logo or a more suitable custom icon.
Also I would like to know if there is any logo for your website at present

**Comment by Abheeshta-P** [comment]
@Jaishree2310 I would like to work on this ! Please assign this to me and also add label hactober and GSSoc label to this

**Comment by Abheeshta-P** [comment]
I would like to know whether currently you have a logo or branding for website if yes, I would implement same in the project

**Comment by Jaishree2310** [comment]
@Abheeshta-P, this issue already exist.
