### ISSUE TITLE
[FEATURE] adding CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by devxMani** [Jaishree2310/GlassyUI-Components#61]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

adding guidelines for contributors

### Proposed Solution

adding guidelines for contributors

### Screenshots

![image](https://github.com/user-attachments/assets/afefdb13-8032-4c7d-8ea2-0c7344fa1a59)

### Do you want to work on this issue?

Yes ADD GSOC ext and hacktoberfest label

### If "yes" to above, please explain how you would technically implement this (issue will not be assigned if this is skipped)

create a file and write about guidelines

**Comment by Jaishree2310** [comment]
@devxMani I have assigned this issue to you. Make sure you keep giving updates on your work.
Happy coding!

**Comment by devxMani** [comment]
@Jaishree2310 i have already done this i have not added this issue let me add then you can see #76 ...
