### ISSUE TITLE
Update Readme.md File

### ISSUE THREAD

**Issue by rajatsinghal02** [Jaishree2310/GlassyUI-Components#69]
I want to update Readme.md file of the Repository.
I want to add these things in File with a Structured Way:
Table of Contents
[Project Overview]
[Features]
[Tech Stack]
[Installation]
[Contributing]
[Pull Request Guidelines]
[Code of Conduct]

@Jaishree2310 Please assign this issue to me .

**Comment by Jaishree2310** [comment]
@rajatsinghal02, This issue already exist.

**Comment by lakshmirajvagu** [comment]
@Jaishree2310 I would like to work on it

**Comment by lakshmirajvagu** [comment]
@Jaishree2310 sure can u keep it as level 2 it will be more helpful to me please I will complete it by tomorrow 🥹
