### ISSUE TITLE
[FEATURE] Automate Greeting Workflow for New Contributors

### ISSUE THREAD

**Issue by archanasingh11** [Jaishree2310/GlassyUI-Components#87]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

## Description

I propose adding an **automated greeting workflow** to welcome first-time contributors when they open their first issue or pull request. The greeting message would include a thank you, brief project introduction, and links to key resources like contribution guidelines and documentation. This would streamline onboarding and ensure all new contributors are welcomed consistently.

### Key Features:
- **Automated Trigger:** Send a greeting when a new contributor opens an issue or PR.
- **Message Content:** Include a welcome note and useful links for contributing.
- **Integration:** Implement using GitHub Actions or a bot like **probot/Welcome**.

Please @Jaishree2310 assign me this task with labels "GSSOC-Ext", "hacktoberfest-accepted" and "level2", "level3".

### Do you want to work on this issue?

Yes

## Benefits

- **Improves onboarding** by making contributors feel appreciated and providing them with key resources.
- **Saves time** by automating a repetitive task for maintainers.
- **Ensures consistency** in welcoming new contributors.

**Comment by Jaishree2310** [comment]
@archanasingh11 I have assigned this issue to you. Make sure you keep giving updates on your work.
Happy coding!
